project_id = "bicorrclgguttsgwxksi"

[functions.execute-workflow]
verify_jwt = false

[functions.upload-logo]
verify_jwt = false

[functions.upload-cat-logo]
verify_jwt = false

[functions.get-workflow-stats]
verify_jwt = false
